blank: {}

up_10:
  237682: ['up', 'Up', '[action: -0.227]', '[action: 0.824]', 'дар', '[action: -0.165]', 'dot', '[action: -0.455]', '构', '串', '种', '종']
  302720: ['raised', 'raise', 'raising', 'larger', 'rais', 'high', 'High', 'Low']
  205792: ['above', 'exceed', 'below', '[action: 0.525]', 'iba', 'ifact', 'less', 'short', 'north', '[action: 0.337]']
  302565: ['North', 'north', 'nord', '[action: -0.831]', 'Nord', 'neutral', '北', 'november', 'sprech', 'norte']
  274043: ['up', 'Up', 'UP', 'upt', 'jusqu', 'fino', 'hasta']
  229524: ['higher', 'ward', 'high', 'lower', 'wards', '[action: -0.957]', 'haut', '段', '[action: -0.596]', '[action: -0.533]']
  246382: ['high', '高', 'High', '[action: 0.792]', 'upper', 'top', 'higher']
  263704: ['Up', 'up', 'Down', 'down', 'rising', '[action: -0.329]', '兴']
  246526: ['northern', 'north', 'south', 'Northern', 'Region', 'ortheast', 'sout', 'southern', 'North', 'Bool']
  285347: ['up', 'high', '[action: -0.894]', '[action: -0.400]', '[action: -0.329]', '[action: -0.957]', '[action: -0.243]', 'High', '高']

up_20:
  237682: ['up', 'Up', '[action: -0.227]', '[action: 0.824]', 'дар', '[action: -0.165]', 'dot', '[action: -0.455]', '构', '串', '种', '종']
  302720: ['raised', 'raise', 'raising', 'larger', 'rais', 'high', 'High', 'Low']
  205792: ['above', 'exceed', 'below', '[action: 0.525]', 'iba', 'ifact', 'less', 'short', 'north', '[action: 0.337]']
  302565: ['North', 'north', 'nord', '[action: -0.831]', 'Nord', 'neutral', '北', 'november', 'sprech', 'norte']
  274043: ['up', 'Up', 'UP', 'upt', 'jusqu', 'fino', 'hasta']
  229524: ['higher', 'ward', 'high', 'lower', 'wards', '[action: -0.957]', 'haut', '段', '[action: -0.596]', '[action: -0.533]']
  246382: ['high', '高', 'High', '[action: 0.792]', 'upper', 'top', 'higher']
  263704: ['Up', 'up', 'Down', 'down', 'rising', '[action: -0.329]', '兴']
  246526: ['northern', 'north', 'south', 'Northern', 'Region', 'ortheast', 'sout', 'southern', 'North', 'Bool']
  285347: ['up', 'high', '[action: -0.894]', '[action: -0.400]', '[action: -0.329]', '[action: -0.957]', '[action: -0.243]', 'High', '高']
  173492: ['high', 'top', '高', 'highest', 'ius', 'upper', 'crown', 'upp', '[action: 0.627]']
  263055: ['up', 'Up', 'pto', 'UP', 'upt', 'jusqu', 'até', 'hasta']
  345008: ['Northern', 'northern', 'negative', 'north', 'Nord', 'Neg', 'nord', '北', 'neg']
  299817: ['up', 'Up', 'UP', '达', 'upp', '喜', 'ὺ']
  245548: ['higher', 'increases', 'increase', 'high', 'highest', 'increased', '高', 'aument', 'High']
  270236: ['up', 'Up', 'ups', 'UP', 'upp', 'upt']
  346069: ['north', 'northern', 'south', 'southern', '[action: 0.573]', '[action: -0.392]', 'east', '[action: -0.612]', '[action: 0.196]', '北']
  258007: ['high', '高', 'highest', 'higher', 'High', 'высо', '[action: 0.212]', 'висо']
  276423: ['up', 'coming', 'Up', 'forth', 'imp', 'kommen', '[action: 0.204]', '麻']
  227857: ['north', 'east', 'North', 'East', 'west', 'Norte', 'south', '北', '[action: 0.925]', 'Left']

careful_10_full:
  167523: ['careful', '[action: -0.894]', 'carefully', '[action: 0.910]', '[action: 0.800]', 'care', '[action: 0.839]', '[action: -0.322]', '[action: 0.745]', '[action: -0.965]']
  179726: ['ca', 'care', 'Care', 'precision', 'careful', 'care', 'Ca', 'ease', '[action: -0.910]', 'ca']
  184404: ['careful', 'ensure', 'carefully', 'avoid', 'avoided', 'cura', 'rup', 'ens', '[action: 0.376]', 'Ens']
  187857: ['carefully', 'correctly', 'careful', 'sufficiently', 'properly', 'luck', 'opport', '[action: 0.298]', 'wrong', '[action: -0.384]']
  196921: ['frag', 'gent', 'gent', 'gentle', 'careful', 'damage', 'care', 'protection', 'prote', 'care']
  206397: ['carefully', 'selected', 'appropriate', 'properly', 'selected', 'quality', 'Selected', 'appropri', 'proven', '[action: 0.957]']
  208658: ['ca', 'avoided', '[action: -0.549]', 'void', 'avoid', 'careful', 'warning', 'ouss', 'це', 'бо']
  210950: ['precision', 'attention', 'rig', 'detail', 'precise', 'met', 'careful', 'strict', 'detail', 'accuracy']
  213398: ['careful', 'wis', 'carefully', 'Wis', 'light', 'hes', 'ca', 'accordingly', 'respons', 'care']
  233026: ['controlled', 'control', 'Control', 'Control', 'control', 'контро', 'controls', '控', 'carefully', 'reprodu']
